In [1]:
import os
import sys
sys.path.insert(0, os.path.abspath('..'))
from libla import Matrix, Vect

In [2]:
X = Matrix.rand_rk(10, 5, 3)

In [3]:
print(X)

Matrix[10,5]{
 [ -0.13   0.58   0.13   0.09  -0.65]
 [  0.54      1    0.7    2.1   0.34]
 [  0.25  -0.13   -1.5   -0.7    1.7]
 [ 0.054    1.4   -1.4  -0.32   0.51]
 [ -0.47    0.6  -0.35  -0.95   -1.1]
 [ -0.29    1.1   0.66    0.4   -1.6]
 [  0.84 -0.056  -0.44    1.3    2.3]
 [  0.24   -1.8  0.046  -0.29    1.3]
 [  0.15  -0.65    1.8    1.4  -0.64]
 [  0.02  -0.92   0.86   0.29  -0.17] 
}


In [4]:
X # Pretty printing by default

Matrix([[-0.12976376,  0.57691315,  0.12944123,  0.08975084, -0.64818211],
        [ 0.54151496,  0.99675512,  0.70317108,  2.07137492,  0.3428745 ],
        [ 0.24943987, -0.1255469 , -1.50646426, -0.70015313,  1.72843878],
        [ 0.05357093,  1.37664882, -1.35359816, -0.31952389,  0.50873136],
        [-0.46711086,  0.5979396 , -0.35398341, -0.95301926, -1.1056094 ],
        [-0.28740141,  1.07974845,  0.65932929,  0.39618038, -1.61877723],
        [ 0.84310303, -0.05623248, -0.43995404,  1.34637536,  2.33217041],
        [ 0.23760821, -1.83289948,  0.04593779, -0.28977186,  1.31749175],
        [ 0.14655227, -0.65439698,  1.76040717,  1.35279495, -0.64031024],
        [ 0.01974819, -0.92492754,  0.85500708,  0.28597869, -0.17095281]])

In [5]:
X[1:3] # Matrix subclasses np.array. So all numpy array operations are available.

Matrix([[ 0.54151496,  0.99675512,  0.70317108,  2.07137492,  0.3428745 ],
        [ 0.24943987, -0.1255469 , -1.50646426, -0.70015313,  1.72843878]])

In [6]:
print(X[1:3])

Matrix[2,5]{
 [  0.54      1    0.7    2.1   0.34]
 [  0.25  -0.13   -1.5   -0.7    1.7] 
}


In [7]:
X.rank()

3

In [8]:
V = Vect.Im(X) # Image vector space
V.dim()

3

In [10]:
V.contains([1,2,3,4,5,6,7,8,9,10]) # Check if vector is contained in image

False

In [11]:
V.contains(X.get_col(0)) # V contains columns of X

True

In [12]:
x = V.project([1,2,3,4,5,6,7,8,9,10]) # Project a vector to V
x

Vect([-0.77538556,  3.13012074, -1.16030557, -2.79290949, -3.19879147,
      -0.99006752,  3.38787505,  2.36208687,  3.96737535,  2.05706154])

In [13]:
V.contains(x)

True